name: CI

on:
  workflow_call:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - run: go mod download
      - run: go vet ./...
      - run: go test -v ./...

  otel:
    permissions:
      contents: read
      actions: read
      pull-requests: read
      checks: read
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    needs: [test-go]
    steps:
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@v4
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
